name: Firebase Functions CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: cd firebase/functions && npm ci

      - name: Dependency Security Audit
        run: cd firebase/functions && npm audit --audit-level=critical


      - name: Run tests
        run: cd firebase/functions && npm run test

      - name: Build
        run: cd firebase/functions && npm run build
